import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Player } from "@remotion/player";
import { Stars } from "../remotion/Stars";
import Download from "../src/components/Download";
import { useRouter } from "next/router";

export default function User() {
  const router = useRouter();
  const username = router.query.user;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {username ? (
        <Player
          component={Stars}
          compositionHeight={1080}
          compositionWidth={1080}
          durationInFrames={300}
          fps={30}
          style={{
            width: 540,
            height: 540,
          }}
          controls
          inputProps={{
            username,
          }}
        ></Player>
      ) : null}
      <Download></Download>
    </div>
  );
}
